---
apiVersion: v1
kind: Service
metadata:
  annotations:
    NDACowner: ""
  labels:
    app: cadvisor
    k8s-app: cadvisor
  name: cadvisor
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
     name: cadvisor


