apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  annotations:
    prometheus.io/scrape: 'true'
  name: node-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
  selector:
    k8s-app: node-exporter